import Vue from 'vue'
import { Tabs, Tab, Checkbox, CheckboxGroup, Badge, Dialog, ActionSheet, Lazyload, Rate, Swipe, SwipeItem, Grid, GridItem, Button, Tabbar, TabbarItem, Icon, NavBar, Toast, Search } from 'vant'

Vue.use(TabbarItem)
Vue.use(Button)
Vue.use(Tabbar)
Vue.use(Icon)
Vue.use(NavBar)
Vue.use(Toast)
Vue.use(Search)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Rate)
Vue.use(Lazyload)
Vue.use(ActionSheet)
Vue.use(Dialog)
Vue.use(Badge)
Vue.use(Checkbox)
Vue.use(CheckboxGroup)
Vue.use(Tab)
Vue.use(Tabs)
